processor PIC16F877A  ; procesador a utilizar
org 0X00              ; Vector de reset
GOTO 0X05             ;Envia PC a la direccion 05
org 0X05              ; Inicio del programa
INICIO                ; Etiqueta INICIO
	BCF 0X03, 0X06    ; BIT CLEAR EN EL REG. DE LA BANDERA PARA ESTAR EN EL BANCO 1
	BSF 0X03, 0X05    ; BIT CLEAR EN EL REG. DE LA BANDERA PARA ESTAR EN EL BANCO 1

	BCF 0X03, 0X00    ; PONER EN 0 EL CARRY
	RLF 0X20          ; DESPLAZAMIENTO A LA IZQUIERDA DEL VALOR DE X (MULTIPLICARLO POR 2)
	BCF 0X03, 0X00    ; PONER EN 0 EL CARRY
	RLF 0X20          ; DESPLAZAMIENTO A LA IZQUIERDA DEL VALOR DE X (MULTIPLICARLO POR 4)

	MOVLW 0X04        ; CARGA LITERAL 0X04 EN W
	SUBWF 0X20,0      ; RESTA DE 4X - 4 Y OBTENEMOS EL VALOR DE Y 

    BCF 0X03, 0X06    ; BIT CLEAR EN EL REG. DE LA BANDERA PARA ESTAR EN EL BANCO 0
	BCF 0X03, 0X05    ; BIT CLEAR EN EL REG. DE LA BANDERA PARA ESTAR EN EL BANCO 0
	SUBWF 0X21, 0     ; COMPARACION DE AMBAS Y
	BTFSS 0X03, 0X02  ; VERIFICAR EL BIT DE LA BANDERA Z DEL STATUS SI 1 PC=PC+1
	GOTO NO_PERTENECE ; NOS SALTAMOS A LAS INSTRUCCIONES PARA EL CASO DE QUE NO PERTENEZCA A LA RECTA
    GOTO PERTENECE    ; NOS DIRIGIMOS A LAS INSTRUCCIONES CUANDO LAS COORDENADAS PERTENECEN A LA RECTA
PERTENECE MOVLW 0XFF  ; CARGA LITERAL 0XFF
          MOVWF 0X06  ; MOVEMOS LA LITERAL A 0X06     
		  GOTO INICIO       ; IR A LA ETIQUETA INICIO
NO_PERTENECE MOVLW 0X00        ; CARGA LITERAL 0X00
             MOVWF 0X06        ; MOVEMOS LA LITERAL A 0X06  
    		 GOTO INICIO       ; IR A LA ETIQUETA INICIO
END                           ; FIN DEL PROGRAMA
	
	
	
