processor PIC16f877A ;procesador a utilizar
org 0x00		;vector de reset
Goto0x05		;envia pc a la direccion 05
org 0x05		;origen del programa

INICIO
	BCF 0X03,0X05;MODIFICAMOS RP0
	BCF 0X03,0X05;MODIFICAMOS RP1
	CLRW ;LIMPIAMOS W
	BCF 0X03, 0 ;COLOCAMOS CARRY EN CERO

	;ENTRO AL BANCO 1
	BSF 0X03, 0X06;MODIFICAMOS RP0
	BCF 0X03, 0X05;MODIFICAMOS RP1
	RLF 0X20 ;MULTIPLICANDO POR DOS
	CLRW;LIMPIAMOS W
	MOVF 0X20, 0 ;PASAMOS A W

	;REGRESO AL BANCO 0
	BCF 0X03, 0X06;MODIFICAMOS RP0
	BCF 0X03, 0X05;MODIFICAMOS RP1

	ADDWF 0X21, 1; SUMAMOS W CON EL REGISTRO Y LO GUARDO EN EL REGISTRO
	MOVLW 0X24	;CARGA LA LITERAL 0X24
	SUBWF 0X21, 0 ;RESTO W CON 0X21 Y GUARDO EN W
	ANDLW 0X0F ;A W OPERO LA LITERAL CON AND Y GUARDO EN W
	;VERIFICAMOS EL RESULTADO
	BTFSS 0X03,2 ;STATUS - BIT DE BANDERA Z
	GOTO Z_UNO ; Significa que el resultado es cero
	GOTO Z_CERO ; Significa que el resultado es dif de cero

Z_UNO	MOVLW 0XFF	;CARGA LA LITERAL 0XFF
		MOVWF 0X24 ;CARGA LA DIRECCIÓN
		GOTO INICIO ;VA ALA ETIQUETA INICIO
Z_CERO	MOVLW 0X00	;CARGA LA LITERAL 0X00
		MOVWF 0X24;CARGA LA DIRECCIÓN
		GOTO INICIO;VA ALA ETIQUETA INICIO
END