processor PIC16F877A  ; procesador a utilizar
org 0X00              ; Vector de reset
GOTO 0X05             ;Envia PC a la direccion 05
org 0X05              ; Inicio del programa
INICIO                ; ETIQUETA INICIO 
	BCF 0X03, 0X05    ; BIT CLEAR EN EL REG. DE LA BANDERA PARA ESTAR EN EL BANCO 0
	BCF 0X03, 0X06    ; BIT CLEAR EN EL REG. DE LA BANDERA PARA ESTAR EN EL BANCO 0
	BTFSS 0X20, 0X07  ; VERIFICAR EL BIT 7 DE LA LOCALIDAD 0X20 SI 1 PC=PC+1
	GOTO UNO_CUATRO   ; ETIQUETA PARA EL CUANDRANTE 1 O 4
	BTFSS 0X21, 0X07  ; VERIFICAR EL BIT 7 DE LA LOCALIDAD 0X21 SI 1 PC=PC+1
	GOTO DOS          ; IR A LA ETIQUETA DOS PARA MOVER EL VALOR EN LA DIRECCION SOLICITADA
	MOVLW 0X03        ; CARGA LITERAL 0X03
	MOVWF 0X23        ; MUEBVE LA LITERAL A 0X23
GOTO INICIO           ; IR A LA ETIQUETA INICIO
DOS MOVLW 0X02        ; CARGA LITERAL 0X02
    MOVWF 0X23        ; MUEBVE LA LITERAL A 0X23
    GOTO INICIO       ; IR A LA ETIQUETA INICIO
UNO_CUATRO BTFSS 0X21, 0X07 ; VERIFICAR EL BIT 7 DE LA LOCALIDAD 0X21 SI 1 PC=PC+1
		   GOTO UNO   ; IR A LA ETIQUETA UNO
		   MOVLW 0X04 ; CARGA LITERAL 0X04
		   MOVWF 0X23 ; MUEBVE LA LITERAL A 0X23
		   GOTO INICIO ; IR A LA ETIQUETA INICIO
		   UNO MOVLW 0X01  ; CARGA LITERAL 0X01
		       MOVWF 0X23  ; MUEBVE LA LITERAL A 0X23
		       GOTO INICIO ; IR A LA ETIQUETA INICIO
END                   ; FIN DEL PROGRAMA 
    